CREATE TABLE `KEYST0320`
(
    `RESERVE_ID`             INT       NOT NULL COMMENT '予約ID',
    `RESERVE_DATE`           DATE      NOT NULL COMMENT '予約日',
    `RESERVE_TIME`           TIME      NOT NULL COMMENT '予約時間',
    `CREATED_DATETIME`       TIMESTAMP NULL DEFAULT NULL COMMENT '作成日時',
    `CREATED_USER`           INT            DEFAULT NULL COMMENT '作成者ID',
    `LAST_MODIFIED_DATETIME` TIMESTAMP NULL DEFAULT NULL COMMENT '最終変更日時',
    `LAST_MODIFIED_USER`     INT            DEFAULT NULL COMMENT '最終変更者ID',
    PRIMARY KEY (`RESERVE_ID`, `RESERVE_DATE`, `RESERVE_TIME`)
) COMMENT = '1on1予約時間';
