CREATE TABLE `KEYST0110`
(
    `USER_ID`                INT          NOT NULL COMMENT 'ユーザーID',
    `QUALIFIED_DATE`         DATE         NULL COMMENT '資格取得年月日',
    `QUALIFICATION_CONTENT`  VARCHAR(255) NULL COMMENT '資格内容',
    `CREATED_DATETIME`       TIMESTAMP    NULL COMMENT '作成日時',
    `CREATED_USER`           INT          NULL COMMENT '作成者ID',
    `LAST_MODIFIED_DATETIME` TIMESTAMP    NULL COMMENT '最終変更日時',
    `LAST_MODIFIED_USER`     INT          NULL COMMENT '最終変更者ID',
    `VERSION_EX_KEY`         INT          NULL DEFAULT 0 COMMENT '排他制御カラム',
    PRIMARY KEY (`USER_ID`),
    UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE
);
