CREATE TABLE `KEYST0100`
(
    `USER_ID`                 INT          NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
    `USER_NAME`               VARCHAR(30)  NOT NULL COMMENT 'ユーザー名',
    `USER_NAME_KANA`          VARCHAR(30)  NOT NULL COMMENT 'ユーザー名かな',
    `TEAM`                    VARCHAR(1)   NULL COMMENT 'チーム',
    `GENDER`                  VARCHAR(1)   NULL COMMENT '性別',
    `AGE`                     INT          NULL COMMENT '年齢',
    `BIRTHDAY`                DATE         NULL COMMENT '生年月日',
    `NATIONALITY`             VARCHAR(30)  NULL COMMENT '国籍',
    `PARTNER_FLG`             VARCHAR(1)   NULL DEFAULT 0 COMMENT '配偶者フラグ',
    `NEAREST_STATION`         VARCHAR(30)  NULL COMMENT '最寄駅',
    `FINAL_EDUCATION_DATE`    DATE         NULL COMMENT '最終学駅年月日',
    `FINAL_EDUCATION_CONTENT` VARCHAR(255) NULL COMMENT '最終学歴内容',
    `SKILLS`                  VARCHAR(30)  NULL COMMENT '保有スキル',
    `EMAIL`                   VARCHAR(255) NULL COMMENT 'メールアドレス',
    `LOGIN_ID`                VARCHAR(255) NOT NULL COMMENT 'ログインID',
    `LOGIN_PW`                VARCHAR(255) NOT NULL COMMENT 'ログインパスワード',
    `ADMIN_FLG`               VARCHAR(1)   NULL COMMENT '管理者フラグ',
    `PRF_IMG_STRG_DRCTRY`     VARCHAR(100) NULL COMMENT 'プロフィール画像格納先ディレクトリ',
    `POSTAL_CODE`             VARCHAR(10)  NULL COMMENT '郵便番号',
    `ADDRESS`                 VARCHAR(255) NULL COMMENT '住所',
    `PHONE_NUMBER`            VARCHAR(255) NULL COMMENT '電話番号',
    `BANK_NAME`               VARCHAR(255) NULL COMMENT '銀行名',
    `BRANCH_NAME`             VARCHAR(255) NULL COMMENT '支店名',
    `BRANCH_ID`               VARCHAR(255) NULL COMMENT '支店番号',
    `ACCOUNT_TYPE`            VARCHAR(255) NULL COMMENT '口座種別',
    `ACCOUNT_NUMBER`          VARCHAR(10)  NULL COMMENT '口座番号',
    `ACCOUNT_NAME`            VARCHAR(255) NULL COMMENT '名義人',
    `DELETE_FLG`              VARCHAR(1)   NULL DEFAULT 0 COMMENT '削除フラグ',
    `CREATED_DATETIME`        TIMESTAMP    NULL COMMENT '作成日時',
    `CREATED_USER`            INT          NULL COMMENT '作成者ID',
    `LAST_MODIFIED_DATETIME`  TIMESTAMP    NULL COMMENT '最終変更日時',
    `LAST_MODIFIED_USER`      INT          NULL COMMENT '最終変更者ID',
    `VERSION_EX_KEY`          INT          NULL DEFAULT 0 COMMENT '排他制御カラム',
    PRIMARY KEY (`USER_ID`),
    UNIQUE INDEX `USER_ID_UNIQUE` (`USER_ID` ASC) VISIBLE,
    UNIQUE INDEX `ACCOUNT_NUMBER_UNIQUE` (`ACCOUNT_NUMBER` ASC) VISIBLE,
    UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
    UNIQUE INDEX `LOGIN_ID_UNIQUE` (`LOGIN_ID` ASC) VISIBLE
) comment ='ユーザー基本情報';
