CREATE TABLE `KEYST0200`
(
    `SKILL_SHEET_ID`         INT          NOT NULL AUTO_INCREMENT,
    `USER_ID`                VARCHAR(8)   NOT NULL,
    `SKILLS`                 VARCHAR(30)  NULL,
    `STRONG_AREA`            VARCHAR(500) NULL,
    `PR`                     VARCHAR(500) NULL,
    `EVALUATION_OF_SALES`    VARCHAR(500) NULL,
    `CREATED_DATETIME`       TIMESTAMP    NULL,
    `CREATED_USER`           VARCHAR(8)   NULL,
    `LAST_MODIFIED_DATETIME` TIMESTAMP    NULL,
    `LAST_MODIFIED_USER`     VARCHAR(8)   NULL,
    `VERSION_EX_KEY`         INT          NULL DEFAULT 0,
    PRIMARY KEY (`SKILL_SHEET_ID`),
    UNIQUE INDEX `SKILL_SHEET_ID_UNIQUE` (`SKILL_SHEET_ID` ASC) VISIBLE
);
